version: 2.1

# Define the jobs we want to run for this project
jobs:
  gas1:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run: sudo docker run bbml/der00

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - gas1